
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: employee_management_development

test:
  <<: *default
  database: employee_management_test

production:
  <<: *default
  database: employee_management_production
